server:
  port: 8081

spring:
  application:
    name: user-center
  datasource:
    url: jdbc:mysql://rm-uf6m7500g66x1ms64eo.mysql.rds.aliyuncs.com:3306/d_user
    hikari:
      username: wanghuanle
      password: wanghuanle
      driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
